name: Build and Deploy Next.js App to Azure Web App - papertrail

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: papertrailr.azurecr.io
  REGISTRY_NAME: papertrailr
  IMAGE_NAME: papertrail
  TAG: latest

permissions:
  id-token: write #This is required for azure/login
  contents: read #This is required for actions/checkout
  
jobs:
  build-and-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Log in to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3032BD0E7994EE5BE3136FFC8DF93DD }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7DBC658F98F4B2F9897A655D56769EB }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BC8232182964DA6946F7B48261482B4 }}

        - name: Log in to Azure Container Registry
          run: az acr login --name ${{ env.REGISTRY_NAME }}

        - name: Build and Push Docker image
          run: |
            docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{ secrets.WEBAPP_NAME }}
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

        - name: AZ CLI logout
          if: always()
          run: |
            az logout